# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: rootdevpass
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - D:\playwrite_project\data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080