# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: rootdevpass
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - D:\playwrite_project\data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080

  caddy:
    image: caddy:alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:433
    volumes:
      - ./app-website/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data:/data
      - ./caddy_config:/config

  website:
    image: website
    restart: always
    tty: true
    build:
      context: ./app-website
      dockerfile: Dockerfile
    working_dir: /usr/src/website
    ports:
      - 8000:8000
    # volumes:
    #   - ./website:/website
    container_name: website
    links:
      - caddy
    entrypoint: ["sh", "/start.sh"]